[[redirects]]
  from = "http://doc.hardwario.com/*"
  to = "https://docs.hardwario.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://doc.hardwario.com/*"
  to = "https://docs.hardwario.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://chester.hardwario.com/*"
  to = "https://docs.hardwario.com/chester"
  status = 301
  force = true

[[redirects]]
  from = "https://chester.hardwario.com/*"
  to = "https://docs.hardwario.com/chester"
  status = 301
  force = true

[[redirects]]
  from = "http://tower.hardwario.com/*"
  to = "https://docs.hardwario.com/tower"
  status = 301
  force = true

[[redirects]]
  from = "https://tower.hardwario.com/*"
  to = "https://docs.hardwario.com/tower"
  status = 301
  force = true

[[redirects]]
  from = "http://cooper.hardwario.com/*"
  to = "https://docs.hardwario.com"
  status = 301
  force = true

[[redirects]]
  from = "https://cooper.hardwario.com/*"
  to = "https://docs.hardwario.com"
  status = 301
  force = true
